### ISSUE TITLE
The reason using reimplemented Euler to Quaternion instead of using scipy

### ISSUE THREAD

**Issue by hallazie** [KosukeFukazawa/smpl2bvh#9]
Hi KosukeFukazawa, great work, it helps me a lot!

I'm quit new to the 3D modeling field, and I'm curios why using the reimplemented approach to convert Euler angles into quaternion (rots = quat.from_axis_angle(rots))? I use scipy's Rotation ( scipy.spatial.transform.Rotation.from_euler().as_quat() ) and yields different result.

And also, in the following code, why convert Euler angles to quaternion and then convert back to Euler angles, instead of directly convert raw Euler angles to degree?

`
    # to quaternion
    rots = quat.from_axis_angle(rots)
    
    order = "zyx"
    pos = offsets[None].repeat(len(rots), axis=0)
    positions = pos.copy()
    positions[:,0] += trans * 100
    rotations = np.degrees(quat.to_euler(rots, order=order))
`

Thanks!

**Comment by KosukeFukazawa** [comment]
Hi hallazie, 
thank you for your interest!

SMPL uses the axis-angle representation (available in scipy as rotvec: https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.transform.Rotation.from_rotvec.html) instead of Euler angles. 
I use quaternion as an intermediate representation because it can prevent gimbal locks, which is useful when adding processing to compensate for motion. (additionally, `scipy.spatial.transform.Rotation` class does not support arrays with dimensions greater than 3, so I implemented a separate solution.)
I think that using scipy to change SMPL's axis-angle representation directly to bvh's Euler angles will give similar results.

**Comment by hallazie** [comment]
> Hi hallazie, thank you for your interest!
> 
> SMPL uses the axis-angle representation (available in scipy as rotvec: https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.transform.Rotation.from_rotvec.html) instead of Euler angles. I use quaternion as an intermediate representation because it can prevent gimbal locks, which is useful when adding processing to compensate for motion. (additionally, `scipy.spatial.transform.Rotation` class does not support arrays with dimensions greater than 3, so I implemented a separate solution.) I think that using scipy to change SMPL's axis-angle representation directly to bvh's Euler angles will give similar results.

Thanks for your reply, that was really helpful, I misunderstood the SMPL default rotation format. Thanks!
